name: Build and Run Docker on AWS

on: [push]

jobs:
  build:
    runs-on: self-hosted  # Runs on AWS Ubuntu instance

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (optional)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-app-container my-app:latest
